### ISSUE TITLE
mix test fail

### ISSUE THREAD

**Issue by gialib** [cconstantin/plug_rails_cookie_session_store#5]
Hi, mix test fail,

I run 

mix deps.update 
mix test

......

  1) test gets and sets custom serialized session cookie (PlugRailsCookieSessionStoreTest)
     test/plug_rails_cookie_session_store_test.exs:175
     Assertion with == failed
     code: conn(:get, "/") |> recycle_cookies(conn) |> custom_serialize_conn() |> get_session(:foo) == "bar"
     lhs:  nil
     rhs:  "bar"
     stacktrace:
       test/plug_rails_cookie_session_store_test.exs:180: (test)

................

Finished in 0.2 seconds
23 tests, 1 failure

**Comment by cconstantin** [comment]
@gialib yeah, I see the failed test, not sure what the cause is though. PR would be appreciated.
