### ISSUE TITLE
Does not work on Rails 4

### ISSUE THREAD

**Issue by sanjiv-hartleylab** [cconstantin/plug_rails_cookie_session_store#9]

**Comment by cconstantin** [comment]
Could you please provide steps to reproduce. Tests that break would be even better. Thanks.

**Comment by paulnicholson** [comment]
I'm not sure exactly what @sanjiv-hartleylab is seeing however I was having issues with Rails 4.2.7 loading a session created by this plug. I solved it by calling `put_session(conn, "session_id", Base.encode16(:crypto.strong_rand_bytes(16), case: :lower))` to add a [session id](https://github.com/rails/rails/blob/v4.2.7/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb#L28). It appears that without a [session id](https://github.com/rails/rails/blob/v4.2.7/actionpack/lib/action_dispatch/middleware/session/cookie_store.rb#L81-L85) Rails doesn't think [session exist](https://github.com/rails/rails/blob/v4.2.7/actionpack/lib/action_dispatch/request/session.rb#L152) when it tries to [load](https://github.com/rails/rails/blob/v4.2.7/actionpack/lib/action_dispatch/request/session.rb#L172) it.

**Comment by fbjork** [comment]
@paulnicholson where did you add the `put_session` call in your app?

**Comment by paulnicholson** [comment]
@fbjork Well, my motivation for getting this to work was rails <-> elixir form posting with csrf validation. I wrote a plug to handle csrf protection in a rails compatible way and that plug ensures the session has a session id. See [gatherdigital/plug_rails_csrf_protection@ff12afd/lib/plug_rails_csrf_protection.ex#L202](https://github.com/gatherdigital/plug_rails_csrf_protection/blob/ff12afd8accc814cf37f021206ee001c5c9e179b/lib/plug_rails_csrf_protection.ex#L202)
